### ISSUE TITLE
0-byte key

### ISSUE THREAD

**Issue by paragonie-scott** [phlib/encrypt#1]
https://github.com/phlib/encrypt/blob/master/src/Encryptor/OpenSsl.php#L108

I've not tested the result of asking hash_pbkdf2() for a 0 byte key and then passing that to openssl_encrypt(), but I'm pretty sure whatever it does isn't good.

(Also, using the same key for encryption and authentication isn't a good idea. If you're using PBKDF2, might as well split the key into two.)

**Comment by Pudge601** [comment]
Hi, thanks for the advice :)

The '0' being passed in to hash_pbkdf2() is the default value for the length, and should mean that the entire output of the algorithm is returned (based on what is described here: http://php.net/manual/en/function.hash-pbkdf2.php#refsect1-function.hash-pbkdf2-parameters).

What you've said about using a separate key for encryption/authentication is a good point, I'll look into what you've suggested about splitting the derived key.

**Comment by paragonie-scott** [comment]
In general: Check out what https://github.com/defuse/php-encryption/tree/v2.0 does. :)
