### ISSUE TITLE
Reuse of key for encryption and authentication

### ISSUE THREAD

**Issue by Pudge601** [phlib/encrypt#2]
As pointed out in issue #1 we should probably be using separate keys for encryption and authentication.

The discussion on this post (http://crypto.stackexchange.com/questions/8081/using-the-same-secret-key-for-encryption-and-authentication-in-a-encrypt-then-ma) suggests that there shouldn't really be any practical issue with using the same for both encryption and authentication, however we may consider doing this just to be on the safe side.

**Comment by paragonie-scott** [comment]
As a precedent, in RSA land, using the same key for signing as encrypting is dangerous.
- http://crypto.stackexchange.com/a/12130
- http://security.stackexchange.com/a/2476

I've yet to see this generalized to an Encryption / MAC issue, but I always remind myself: "Attacks only get better."
